-- Copyright (c) 2023 - Gesma94
-- This code is licensed under CC BY-NC-ND 4.0 license (see LICENSE for details)

DROP TYPE IF EXISTS "auction_mode" CASCADE;
DROP TYPE IF EXISTS "player_role" CASCADE;
DROP TYPE IF EXISTS "auction_status" CASCADE;
DROP TYPE IF EXISTS "auction_call_order" CASCADE;
DROP TYPE IF EXISTS "batch_status" CASCADE;
DROP TABLE IF EXISTS "Auctions" CASCADE;
DROP TABLE IF EXISTS "Batches" CASCADE;
DROP TABLE IF EXISTS "Footballers" CASCADE;
DROP TABLE IF EXISTS "Footballers_Users" CASCADE;
DROP TABLE IF EXISTS "Offers" CASCADE;
DROP TABLE IF EXISTS "Users_Auctions" CASCADE;
DROP TABLE IF EXISTS "Users" CASCADE;
DROP TABLE IF EXISTS "User_Recovery_Guids" CASCADE;
DROP INDEX IF EXISTS "Uniqueness--Footballers--first_name-last_name-auction_id" CASCADE;

CREATE TYPE "auction_mode" AS ENUM (
  'turn_based',
  'offer_based'
);

CREATE TYPE "player_role" AS ENUM (
  'goalkeeper',
  'defender',
  'midfielder',
  'striker'
);

CREATE TYPE "auction_status" AS ENUM (
  'created',
  'started',
  'ended'
);

CREATE TYPE "auction_call_order" AS ENUM (
  'by_role',
  'unordered'
);

CREATE TYPE "batch_status" AS ENUM (
  'created',
  'started',
  'ended'
);

CREATE TABLE "Auctions" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
    "created_time" timestamptz NOT NULL,
    "last_modified_time" timestamptz NOT NULL,
    "status" auction_status NOT NULL,
    "name" varchar UNIQUE NOT NULL,
    "user_size" integer NOT NULL,
    "initial_credit" integer NOT NULL,
    "mode" auction_mode NOT NULL,
    "call_order" auction_call_order NOT NULL,
    "users_order" integer[],
    "offer_based_timeout_cal_ms" integer,
    "goalkeeper_min_amount" integer NOT NULL,
    "goalkeeper_max_amount" integer NOT NULL,
    "defender_min_amount" integer NOT NULL,
    "defender_max_amount" integer NOT NULL,
    "midfielder_min_amount" integer NOT NULL,
    "midfielder_max_amount" integer NOT NULL,
    "striker_min_amount" integer NOT NULL,
    "striker_max_amount" integer NOT NULL
);

CREATE TABLE "Batches" (
   "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
   "created_time" timestamptz NOT NULL,
   "last_modified_time" timestamptz NOT NULL,
   "auction_id" integer NOT NULL,
   "footballer_id" integer NOT NULL,
   "initial_cost" integer NOT NULL,
   "last_caller_offer" integer NOT NULL,
   "last_caller_user_id" integer NOT NULL,
   "next_caller_user_id" integer NOT NULL,
   "status" batch_status NOT NULL,
   "folded_users_id" integer[] NOT NULL
);

CREATE TABLE "Footballers" (
   "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
   "created_time" timestamptz NOT NULL,
   "last_modified_time" timestamptz NOT NULL,
   "auction_id" integer NOT NULL,
   "first_name" varchar NOT NULL,
   "last_name" varchar NOT NULL,
   "price" integer NOT NULL,
   "role" player_role NOT NULL
);

CREATE TABLE "Footballers_Users" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
    "created_time" timestamptz NOT NULL,
    "last_modified_time" timestamptz NOT NULL,
    "footballer_id" integer NOT NULL,
    "user_id" integer NOT NULL
);

CREATE TABLE "Offers" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
    "created_time" timestamptz NOT NULL,
    "last_modified_time" timestamptz NOT NULL,
    "batch_id" integer NOT NULL,
    "user_id" integer NOT NULL,
    "previous_offer_id" integer,
    "offered_amount" integer NOT NULL
);

CREATE TABLE "Users_Auctions" (
    "user_id" integer NOT NULL,
    "created_time" timestamptz NOT NULL,
    "last_modified_time" timestamptz NOT NULL,
    "auction_id" integer NOT NULL,
    "is_admin" boolean NOT NULL,
    PRIMARY KEY ("user_id", "auction_id")
);

CREATE TABLE "Users" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
    "created_time" timestamptz NOT NULL,
    "last_modified_time" timestamptz NOT NULL,
    "email" varchar UNIQUE NOT NULL,
    "username" varchar UNIQUE NOT NULL,
    "password" varchar NOT NULL,
    "date_of_birth" date,
    "favourite_team" varchar,
    "city" varchar
);

CREATE TABLE "User_Recovery_Guids" (
   "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
   "user_id" integer NOT NULL,
   "guid" uuid NOT NULL,
   "timestamp" timestamptz NOT NULL
);

CREATE UNIQUE INDEX "Uniqueness--Footballers--first_name-last_name-auction_id" ON "Footballers" ("first_name", "last_name", "auction_id");

ALTER TABLE "Batches" ADD FOREIGN KEY ("auction_id") REFERENCES "Auctions" ("id");

ALTER TABLE "Batches" ADD FOREIGN KEY ("footballer_id") REFERENCES "Footballers" ("id");

ALTER TABLE "Batches" ADD FOREIGN KEY ("last_caller_user_id") REFERENCES "Users" ("id");

ALTER TABLE "Batches" ADD FOREIGN KEY ("next_caller_user_id") REFERENCES "Users" ("id");

ALTER TABLE "Footballers" ADD FOREIGN KEY ("auction_id") REFERENCES "Auctions" ("id");

ALTER TABLE "Footballers_Users" ADD FOREIGN KEY ("footballer_id") REFERENCES "Footballers" ("id");

ALTER TABLE "Footballers_Users" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");

ALTER TABLE "Offers" ADD FOREIGN KEY ("batch_id") REFERENCES "Batches" ("id");

ALTER TABLE "Offers" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");

ALTER TABLE "Offers" ADD FOREIGN KEY ("previous_offer_id") REFERENCES "Offers" ("id");

ALTER TABLE "Users_Auctions" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");

ALTER TABLE "Users_Auctions" ADD FOREIGN KEY ("auction_id") REFERENCES "Auctions" ("id");

ALTER TABLE "User_Recovery_Guids" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");
