CREATE TYPE "auction_mode" AS ENUM (
  'turn_based',
  'real_time'
);

CREATE TYPE "player_role" AS ENUM (
  'goalkeper',
  'defender',
  'midfielder',
  'striker'
);

CREATE TYPE "auction_status" AS ENUM (
  'initialized',
  'in_lobby',
  'created',
  'started',
  'ended'
);

CREATE TYPE "player_call_order_mode" AS ENUM (
  'by_role',
  'unordered'
);

CREATE TYPE "batch_status" AS ENUM (
  'ongoing',
  'end'
);

CREATE TABLE "Users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "reset_password_guid" uuid,
  "reset_password_timestamp" timestamptz,
  "email" varchar UNIQUE NOT NULL,
  "username" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "creation_date" timestamptz NOT NULL,
  "date_of_birth" date,
  "favourite_team" varchar,
  "city" varchar
);

CREATE TABLE "Users_Auctions" (
  "user_id" integer NOT NULL,
  "auction_id" integer NOT NULL,
  "is_admin" boolean NOT NULL,
  PRIMARY KEY ("user_id", "auction_id")
);

CREATE TABLE "Footballers" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "auction_id" integer NOT NULL,
  "user_owner_id" integer,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "price" integer NOT NULL,
  "role" player_role NOT NULL
);

CREATE TABLE "Batches" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "creation_date" timestamptz NOT NULL,
  "auction_id" integer NOT NULL,
  "footballer_id" integer NOT NULL,
  "current_cost" integer NOT NULL,
  "current_owner_user_id" integer NOT NULL,
  "initial_cost" integer NOT NULL,
  "status" batch_status NOT NULL,
  "folded_users_id" integer[] NOT NULL,
  "next_caller_user_id" integer NOT NULL,
  "winner_user_id" integer
);

CREATE TABLE "Offers" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "batch_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "previous_amount" integer,
  "offered_amount" integer NOT NULL,
  "creation_date" timestamptz NOT NULL
);

CREATE TABLE "Auctions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "creation_date" timestamptz NOT NULL,
  "status" auction_status NOT NULL,
  "name" varchar UNIQUE NOT NULL,
  "user_amount" integer NOT NULL,
  "initial_credit" integer NOT NULL,
  "mode" auction_mode NOT NULL,
  "users_order" integer[],
  "realtime_timeout_call_ms" integer,
  "goalkeaper_min_amount" integer,
  "goalkeaper_max_amount" integer,
  "defender_min_amount" integer,
  "defender_max_amount" integer,
  "midfielder_min_amount" integer,
  "midfielder_max_amount" integer,
  "striker_min_amount" integer,
  "striker_max_amount" integer
);

CREATE UNIQUE INDEX "Uniqueness--Footballers--first_name-last-name" ON "Footballers" ("first_name", "last_name");

ALTER TABLE "Users_Auctions" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");

ALTER TABLE "Users_Auctions" ADD FOREIGN KEY ("auction_id") REFERENCES "Auctions" ("id");

ALTER TABLE "Footballers" ADD FOREIGN KEY ("auction_id") REFERENCES "Auctions" ("id");

ALTER TABLE "Footballers" ADD FOREIGN KEY ("user_owner_id") REFERENCES "Users" ("id");

ALTER TABLE "Batches" ADD FOREIGN KEY ("auction_id") REFERENCES "Auctions" ("id");

ALTER TABLE "Batches" ADD FOREIGN KEY ("footballer_id") REFERENCES "Footballers" ("id");

ALTER TABLE "Batches" ADD FOREIGN KEY ("current_owner_user_id") REFERENCES "Users" ("id");

ALTER TABLE "Batches" ADD FOREIGN KEY ("next_caller_user_id") REFERENCES "Users" ("id");

ALTER TABLE "Batches" ADD FOREIGN KEY ("winner_user_id") REFERENCES "Users" ("id");

ALTER TABLE "Offers" ADD FOREIGN KEY ("batch_id") REFERENCES "Batches" ("id");

ALTER TABLE "Offers" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");
